POSTGRES_DB=spacepod
POSTGRES_USER=spacepod
POSTGRES_PASSWORD=rahmeekiS3shaiTh
POSTGRES_HOST=localhost
POSTGRES_PORT=10010

PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -p $POSTGRES_PORT -U $POSTGRES_USER $POSTGRES_DB
